// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoListWebApi.Context;

#nullable disable

namespace TodoListWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231016093356_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoListWebApi.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Work")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9306),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9296),
                            IsCompleted = false,
                            Work = "Get to work"
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9309),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9308),
                            IsCompleted = false,
                            Work = "Pick up groceries"
                        },
                        new
                        {
                            Id = 3,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9310),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9310),
                            IsCompleted = false,
                            Work = "Go home"
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9312),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9312),
                            IsCompleted = false,
                            Work = "Fall asleep"
                        },
                        new
                        {
                            Id = 5,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9314),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9313),
                            IsCompleted = true,
                            Work = "Get up"
                        },
                        new
                        {
                            Id = 6,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9315),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9315),
                            IsCompleted = true,
                            Work = "Brush teeth"
                        },
                        new
                        {
                            Id = 7,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9318),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9317),
                            IsCompleted = true,
                            Work = "Take a shower"
                        },
                        new
                        {
                            Id = 8,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9319),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9319),
                            IsCompleted = true,
                            Work = "Check e-mail"
                        },
                        new
                        {
                            Id = 9,
                            CompletedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9321),
                            CreatedAt = new DateTime(2023, 10, 16, 12, 33, 56, 425, DateTimeKind.Local).AddTicks(9320),
                            IsCompleted = true,
                            Work = "Walk dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
